on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동실행

name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
#       - uses: samin/mysql-action@v1
#         with:
#           entryPoint: database.ciqb044yewhm.ap-northeast-2.rds.amazonaws.com
#           mysql version: '8.0.27' # Optional, default value is "latest". The version of the MySQL
#           mysql database: 'capstone2' # Optional, default value is "test". The specified database which will be create
#           mysql user: 'admin' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Of course you can use secrets, too
#           mysql password: ${{ secrets.DATABASE_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0.27' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'jdbc:mysql://database.ciqb044yewhm.ap-northeast-2.rds.amazonaws.com:3306/capstone2' # Optional, default value is "test". The specified database which will be create
          mysql user: 'admin' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.DATABASE_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
